# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamestat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgm', models.IntegerField()),
                ('pos', models.IntegerField()),
                ('fg_field', models.DecimalField(db_column='fg_', decimal_places=3, max_digits=4)),
                ('pf', models.IntegerField()),
                ('field_3pm', models.IntegerField(db_column='_3pm')),
                ('status', models.CharField(max_length=7)),
                ('stl', models.IntegerField()),
                ('opponent', models.CharField(max_length=16)),
                ('tov', models.IntegerField()),
                ('orb', models.IntegerField()),
                ('field_date', models.DateTimeField(db_column='_date')),
                ('fta', models.IntegerField()),
                ('fic', models.DecimalField(decimal_places=1, max_digits=3)),
                ('w_l', models.CharField(max_length=1)),
                ('drb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('field_min', models.IntegerField(db_column='_min')),
                ('team', models.CharField(max_length=13)),
                ('blk', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('ft_field', models.DecimalField(db_column='ft_', decimal_places=3, max_digits=4)),
                ('ftm', models.IntegerField()),
                ('field_3p_field', models.DecimalField(db_column='_3p_', decimal_places=3, max_digits=4)),
                ('field_3pa', models.IntegerField(db_column='_3pa')),
                ('reb', models.IntegerField()),
            ],
            options={
                'db_table': 'gamestats',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('yos', models.IntegerField()),
                ('pos', models.IntegerField()),
                ('height', models.IntegerField()),
                ('draft_status', models.DecimalField(decimal_places=3, max_digits=7)),
                ('player', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('current_team', models.CharField(max_length=22)),
                ('nationality', models.CharField(max_length=32)),
                ('weight', models.IntegerField()),
                ('pre_draft_team', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.AddField(
            model_name='gamestat',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='data.Player'),
        ),
    ]
