# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player',
            new_name='name',
        ),
    ]
