# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160128_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestat',
            options={'ordering': ['-field_date']},
        ),
    ]
