# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160128_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=5)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamestat',
            options={'ordering': ['-field_date']},
        ),
    ]
