# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_positions(apps, schema_editor):
    POSITIONS = (
        (1, 'PG', 'Point Guard'),
        (2, 'G', 'Guard'),
        (3, 'SG', 'Shooting Guard'),
        (4, 'GF', 'Guard/Forward'),
        (5, 'SF', 'Small Forward'),
        (6, 'F', 'Forward'),
        (7, 'PF', 'Power Forward'),
        (8, 'FC', 'Forward/Center'),
        (10, 'C', 'Center'),
    )

    Position = apps.get_model("data", "Position")
    for position in POSITIONS:
        p = Position(
            id=position[0],
            short_name=position[1],
            long_name=position[2]
        )
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160128_2145'),
    ]

    operations = [
        migrations.RunPython(create_positions),
        migrations.AlterField(
            model_name='gamestat',
            name='pos',
            field=models.ForeignKey(db_column='pos', on_delete=django.db.models.deletion.CASCADE, to='data.Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pos',
            field=models.ForeignKey(db_column='pos', on_delete=django.db.models.deletion.CASCADE, to='data.Position'),
        ),
    ]
