# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20160128_2146'),
        ('data', '0004_auto_20160128_2207'),
    ]

    operations = [
    ]
